[package]
name = "starknet-static-analysis"
version = "0.1.0"
rust-version = "1.66"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0" }
clap = { version = "4.1" }
serde_json = { version = "1.0" }
num-bigint = { version = "0.4" }
num-traits = { version = "0.2" }
once_cell = { version = "1.17" }
smol_str = { version = "0.2" }
num-integer = { version = "0.1" }

cairo-lang-compiler = { git = "https://github.com/starkware-libs/cairo.git", rev = "834df7e" }
cairo-lang-defs = { git = "https://github.com/starkware-libs/cairo.git", rev = "834df7e" }
cairo-lang-plugins = { git = "https://github.com/starkware-libs/cairo.git", rev = "834df7e" }
cairo-lang-starknet = { git = "https://github.com/starkware-libs/cairo.git", rev = "834df7e" }
cairo-lang-filesystem = { git = "https://github.com/starkware-libs/cairo.git", rev = "834df7e" }
cairo-lang-parser = { git = "https://github.com/starkware-libs/cairo.git", rev = "834df7e" }
cairo-lang-syntax = { git = "https://github.com/starkware-libs/cairo.git", rev = "834df7e" }
cairo-lang-semantic = { git = "https://github.com/starkware-libs/cairo.git", rev = "834df7e" }
cairo-lang-utils = { git = "https://github.com/starkware-libs/cairo.git", rev = "834df7e" }
cairo-lang-sierra-generator = { git = "https://github.com/starkware-libs/cairo.git", rev = "834df7e" }
cairo-lang-sierra = { git = "https://github.com/starkware-libs/cairo.git", rev = "834df7e" }


# For -Zminimal-versions
string_cache = "0.8.4"
io-lifetimes = "1.0.2"
bit-vec = "0.6.3"
rustix = "0.36.9"
fnv = "1.0.5"


[dev-dependencies]
insta = { version = "1.29", features = ["glob"] }

[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3

# For dylint
[workspace.metadata.dylint]
libraries = [
    { git = "https://github.com/trailofbits/dylint", pattern = "examples/general/*" },
    { git = "https://github.com/trailofbits/dylint", pattern = "examples/supplementary/*" },
    { git = "https://github.com/trailofbits/dylint", pattern = "examples/restriction/collapsible_unwrap" },
    { git = "https://github.com/trailofbits/dylint", pattern = "examples/restriction/const_path_join" },
    { git = "https://github.com/trailofbits/dylint", pattern = "examples/restriction/env_literal" },
    { git = "https://github.com/trailofbits/dylint", pattern = "examples/restriction/inconsistent_qualification" },
    { git = "https://github.com/trailofbits/dylint", pattern = "examples/restriction/misleading_variable_name" },
    # { git = "https://github.com/trailofbits/dylint", pattern = "examples/restriction/missing_doc_comment_openai" },
    { git = "https://github.com/trailofbits/dylint", pattern = "examples/restriction/question_mark_in_expression" },
    { git = "https://github.com/trailofbits/dylint", pattern = "examples/restriction/ref_aware_redundant_closure_for_method_calls" },
    { git = "https://github.com/trailofbits/dylint", pattern = "examples/restriction/suboptimal_pattern" },
]