[package]
name = "starknet-static-analysis"
version = "0.1.0"
rust-version = "1.66"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.70" }
clap = { version = "4.1.4"}

cairo-lang-compiler = { git = "https://github.com/starkware-libs/cairo.git", rev = "9c19056" }
cairo-lang-defs = { git = "https://github.com/starkware-libs/cairo.git", rev = "9c19056" }
cairo-lang-plugins = { git = "https://github.com/starkware-libs/cairo.git", rev = "9c19056" }
cairo-lang-starknet = { git = "https://github.com/starkware-libs/cairo.git", rev = "9c19056" }
cairo-lang-filesystem = { git = "https://github.com/starkware-libs/cairo.git", rev = "9c19056" }
cairo-lang-parser = { git = "https://github.com/starkware-libs/cairo.git", rev = "9c19056" }
cairo-lang-syntax = { git = "https://github.com/starkware-libs/cairo.git", rev = "9c19056" }
cairo-lang-semantic = { git = "https://github.com/starkware-libs/cairo.git", rev = "9c19056" }
cairo-lang-utils = { git = "https://github.com/starkware-libs/cairo.git", rev = "9c19056" }
cairo-lang-sierra-generator = { git = "https://github.com/starkware-libs/cairo.git", rev = "9c19056" }
cairo-lang-sierra = { git = "https://github.com/starkware-libs/cairo.git", rev = "9c19056" }

# For -Zminimal-versions
string_cache = "0.8.4"
io-lifetimes = "1.0.2"
bit-vec = "0.6.3"
good_lp = "1.4.0"
rustix = "0.36.9"
fnv = "1.0.5"
